import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

import { CustomSessionProvider } from "@/components/providers/session-provider";
import { UserProvider } from "@/context/user-context";
import Header from "@/components/header/page";

import { getServerAuthSession } from "@/lib/auth";
import { prisma } from "@/lib/db";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI SAAS PLATFORM",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // ✅ Get session on server
  const session = await getServerAuthSession();

  // ✅ Fetch user from DB if logged in
  let user = null;
  if (session?.user?.email) {
    user = await prisma.user.findUnique({
      where: { email: session.user.email },
      select: {
        name: true,
        role: true,
        plan: true,
        credits: true,
      },
    });
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Razorpay checkout script */}
        <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="afterInteractive"
        />

        {/* ✅ NextAuth session */}
        <CustomSessionProvider>
          {/* ✅ GLOBAL USER CONTEXT */}
          <UserProvider
            initialName={user?.name ?? undefined}
            initialRole={user?.role ?? undefined}
            initialPlan={user?.plan ?? "FREE"}
            initialCredits={user?.credits ?? 0}
          >
            {/* ✅ Single global navbar */}
            <Header />

            {/* ✅ All pages */}
            {children}
          </UserProvider>
        </CustomSessionProvider>
      </body>
    </html>
  );
}
